name: elliptic
description: basic elliptic curves
version: 0.3.7
homepage: https://github.com/C0MM4ND/dart-elliptic

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
